version: "3"
services:
  b2-prep:
    image: b2:latest
    network_mode: host
    environment:
      - INSERT_COMMITS_AFTER=1000
      - TEMP_TABLE_PREP_SIZE_RATIO=0.80
      - PREP_PHASE_CHUNK_SIZE=10000
      - TEMP_TABLE_RUN_SIZE_RATIO=0.25
      - RUN_PHASE_PUBLISH_CHUNK_SIZE=10000
    command:
      [
        "./bombard",
        "-v=2",
        "-stderrthreshold=INFO",
        "--host",
        "localhost",
        "--experiment-host",
        "localhost",
        "--username",
        "root",
        "--password",
        "ilapahsi",
        "--port",
        "3306",
        "--database",
        "rickilap",
        "--tablename",
        "helloworld",
        "--prepare",
      ]
  b2-run:
    image: b2:latest
    network_mode: host
    environment:
      - INSERT_COMMITS_AFTER=1000
      - TEMP_TABLE_PREP_SIZE_RATIO=0.80
      - PREP_PHASE_CHUNK_SIZE=10000
      - TEMP_TABLE_RUN_SIZE_RATIO=0.25
      - RUN_PHASE_PUBLISH_CHUNK_SIZE=10000
      - TIME_SERIES_TICK_MS=1000
      - METRIC_POLL_TICK_MS=1000
    command:
      [
        "./bombard",
        "-v=2",
        "-stderrthreshold=INFO",
        "--host",
        "localhost",
        "--experiment-host",
        "localhost",
        "--username",
        "root",
        "--password",
        "ilapahsi",
        "--port",
        "3306",
        "--database",
        "rickilap",
        "--time",
        "1",
        "--tablename",
        "helloworld",
        "--read-cpm",
        "1000",
        "--create-cpm",
        "2000",
        "--run",
      ]
