version: "3"
services:
  c4-debug:
    image: c4-debug:latest
    network_mode: host
    environment:
      - INSERT_COMMITS_AFTER=1000
      - TEMP_TABLE_PREP_SIZE_RATIO=0.80
      - PREP_PHASE_CHUNK_SIZE=10000
      - TEMP_TABLE_RUN_SIZE_RATIO=0.25
      - RUN_PHASE_PUBLISH_CHUNK_SIZE=10000
      - RUN_PHASE_PUBLISH_SLEEP_TIME=200
      - RUN_PHASE_SUBSCRIBE_SLEEP_TIME=100
    command:
      [
        "./bombard",
        "-v=2",
        "-stderrthreshold=INFO",
        "--host",
        "localhost",
        "--experiment-host",
        "localhost",
        "--username",
        "root",
        "--password",
        "root",
        "--port",
        "3306",
        "--database",
        "bigbasket",
        "--tablename",
        "membercommunication_membercommunicationlog",
        "--prepare",
      ]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.8"
          memory: 800M
